server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: 123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.springcloud.userservice.entity
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka