spring:
  application:
    name: eureka-server
server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false #是否注册自身
    registry-fetch-interval-seconds: 5 #重新拉去服务列表时间间隔
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 90 #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30 #服务续约(renew)的间隔，默认为30秒
